### ISSUE TITLE
The tag <block> is unrecognized in this browser.

### ISSUE THREAD

**Issue by LukeSchlangen** [xvicmanx/react-blockly-drawer#1]
This was really easy to get started! Thank you so much for creating this. When I check the console, I'm getting three warnings:

- `Warning: The tag <block> is unrecognized in this browser. If you meant to render a React component, start its name with an uppercase letter.`
- `Warning: The tag <category> is unrecognized in this browser. If you meant to render a React component, start its name with an uppercase letter.`
- `Warning: The tag <xml> is unrecognized in this browser. If you meant to render a React component, start its name with an uppercase letter.`

It looks like the DOM shows those three elements in the blockly area, and that makes sense to me. I'm wondering if there is a way to prevent React from inspecting these elements?

<img width="487" alt="screen shot 2018-01-26 at 2 07 10 pm" src="https://user-images.githubusercontent.com/5384581/35458586-8e48df42-02a2-11e8-88d4-9c10074a5138.png">

I'm definitely willing to make a PR if I can figure out where to start. Have you seen this or tried to resolve it before? Is it something I should learn to ignore?

**Comment by xvicmanx** [comment]
Thank you very much for reporting it. I will take a look.

**Comment by xvicmanx** [comment]
I made some small changes: In order to include predefined tools it would be necessary to import:

`import BlocklyDrawer, { Block, Category } from 'react-blockly-drawer';`

and use them like:

```
<Category name="values">
      <Block  type="text" />
</Category>
```
and so 

```
<BlocklyDrawer
      tools={[helloWorld]}
      onChange={(code, workspace) => {
        console.log(code, workspace);
      }}
    >
      <Category name="Variables" custom="VARIABLE" />
      <Category name="Values">
        <Block type="math_number" />
        <Block type="text" />
      </Category>
    </BlocklyDrawer>
```

This changes were published in the new version of the package (**1.4.0**)

**Comment by teleginzhenya** [comment]
@xvicmanx Hello! Thank you for your work, however it seems that problem still exists.

![image](https://user-images.githubusercontent.com/24455680/40465812-7a48609a-5f44-11e8-8955-902e1e3a51ac.png)

**Comment by xvicmanx** [comment]
Hello @teleginzhenya,
Does this error happen even using the uppercase components?

`import BlocklyDrawer, { Block, Category } from 'react-blockly-drawer';`

**Comment by teleginzhenya** [comment]
@xvicmanx yes, it is.
Here is the [gist](https://gist.github.com/teleginzhenya/5942edede287b4abb1316158b2876cfd).
Also, if I remove `tools={[helloWorld]}` there will be only `xml` warning
![Empty xml is created](https://user-images.githubusercontent.com/24455680/40482502-e49bdd5a-5f76-11e8-9e70-ef5c8e93aa69.png)
_empty xml is created_

**Comment by hypno7oad** [comment]
> @xvicmanx yes, it is.

For what it's worth, I am also getting this error. However, it only appears if `<BlocklyDrawer>` is nested underneath other components.
e.g. `<div><header><BlocklyDrawer /></header></div>` won't work, but if `<BlocklyDrawer>` is the only thing being rendered, then everything is fine.

**Comment by charisra** [comment]
I'm having this issue even when <BlocklyDrawer> is not nested. 
Has anyone found a solution? And why is this issue closed? It's clearly not fixed. I suggest re-opening it @xvicmanx 
Edit: After a small search, I found that the tags have to be submitted for whitelisting in React. [Here's a similar issue](https://github.com/facebook/react/issues/13299), resolved. Looking for other workarounds.

**Comment by hichana** [comment]
Hello @xvicmanx -- I was able to stop the warnings described in this issue by doing the following:

**In ToolBoxTagsComponents.js I replaced this:**
```
export const Block = (props) => {
    return React.createElement('block', props)
};
export const Category = (props) => {
    return React.createElement('category', props);
};

class XmlComponent extends Component {
    render() {
        const injectedProps = Object.assign(
            {},
            this.props,
            {
                ref: (x) => this.props.onRef(x)
            });
        delete injectedProps.onRef;
        return React.createElement('xml', injectedProps);
    }
};
```

**with this:**

```
export const Block = (p) => {
    const { children, ...props } = p;
    props.is = "blockly";
    return React.createElement("block", props, children);
};

export const Category = (p) => {
    const { children, ...props } = p;
    props.is = "blockly";
    return React.createElement("category", props, children);
};


class XmlComponent extends Component {
    render() {
        const injectedProps = Object.assign(
            {},
            this.props,
            {
                ref: (x) => this.props.onRef(x)
            });
        delete injectedProps.onRef;
        injectedProps.is = "blockly";
        return React.createElement('xml', injectedProps);
    }
};

```

I manually imported the files from your package into my project instead of using the package import, and with the change I just mentioned there are no errors anymore. I'm just getting started with Blockly, but it seems like each element just needed to get told that it's a 'blockly' component. I was digging around the Google sample react repo and this is where I saw them using the same method: https://github.com/google/blockly-samples/blob/master/examples/blockly-react/src/Blockly/index.js

**Comment by xvicmanx** [comment]
Thank you very much for finding this @hichana. Feel free to create a PR with the fix or I can do it later.

**Comment by hichana** [comment]
Welcome @xvicmanx , thank you for making this package in the first place. I made the PR. I've never made a PR before so not sure if I'm doing it right. I think the changes are simple enough that it should work.
