### ISSUE TITLE
BlocklyDrawer always has an offset to his parent Div

### ISSUE THREAD

**Issue by MaxBotta** [xvicmanx/react-blockly-drawer#11]
Hello, I have a problem with the offset of the BlocklyDrawer component. Always when I add the component, it has an initial offset to its parent.

<img width="1280" alt="bildschirmfoto 2018-05-25 um 13 37 01" src="https://user-images.githubusercontent.com/18328038/40542534-ce97e4b8-6020-11e8-97fc-7d97a27bf3c0.png">

I was able to fix this problem by setting x and y in the BlocklyDrawer to 0, but I don't want to change the code in the Module. Do you have a suggestion how I can fix this problem?

```
key: 'onResize',
    value: function onResize() {
      var x = 0;
      var y = 0;
      var element = this.wrapper;
      do {
        x += element.offsetLeft;
        y += element.offsetTop;
        element = element.offsetParent;
      } while (element);

      // this.content.style.left = x + 'px';
      //this.content.style.top = y + 'px';
      this.content.style.left = 0 + 'px';
      this.content.style.top = 0 + 'px';
      this.content.style.width = this.wrapper.offsetWidth + 'px';
      this.content.style.height = this.wrapper.offsetHeight + 'px';
    }
```

**Comment by xvicmanx** [comment]
Hello Max,
Could you provide a what are the css properties of the drawer component parent?
This is to try to replicate the issue.

**Comment by MaxBotta** [comment]
The parent only has two properties:

```
#blockly-container {
    width: 100%;
    height: 100%;
}
```

The component is placed inside a Div like this:
```
 render() {
    if ( this.props.tab == undefined || this.props.tabs[this.props.tab].isActive) {
      return (
        <div id="blockly-container">
          <BlocklyDrawer
            
            tools={[
              blocks.rotate,
              blocks.turn,
              blocks.face,
              blocks.draw_face
            ]}
            workspaceXML={this.props.workspace}
            onChange={(code, workspace) => {
              this.setWorkspaceAndCode(code, workspace);
            }}
            appearance={{
              categories: {
                Movement: {
                  colour: '180'
                },
                Sounds: {
                  colour: '290'
                },
                Emotions: {
                  colour: '345'
                },
              },
            }}
          >

            <Category name="Logic" colour="210">
              <Block type="logic_compare"></Block>
              <Block type="logic_operation"></Block>
              <Block type="logic_boolean"></Block>
              <Block type="controls_if"></Block>
            </Category>

            <Category name="Text" colour="160">
              <Block type="text"></Block>
            </Category>

            <Category name="Control" colour="120">
              <Block type="controls_whileUntil"></Block>
              <Block type="controls_for"></Block>
              <Block type="controls_repeat_ext"></Block>
            </Category>

            <Category name="Math" colour="230">
              <Block type="math_number"></Block>
            </Category>

            <Category name="Variables" colour="330" custom="VARIABLE"></Category>
            <Category name="Functions" custom="PROCEDURE" colour="290"></Category>
          </BlocklyDrawer>

          <div id="btn-container">
            <div id="showCode" className="btn-blockly-editor fa fa-code" onClick={this.showCode}></div>
            <div id="runCode" className="btn-blockly-editor fa fa-download" onClick={this.showCode}></div>
            <div id="saveCode" className="btn-blockly-editor fa fa-save" onClick={this.showCode}></div>
            <div id="openCode" className="btn-blockly-editor fa fa-folder" onClick={this.showCode}></div>
          </div>
        </div>
        
      );
    } else {
      return null;
    }
  }
}

export default BlocklyEditor;
```

When I inspect the webpage, I can see, that the content has an offset of 44px on the top and 55px on the left:

<img width="1280" alt="bildschirmfoto 2018-05-25 um 19 42 14" src="https://user-images.githubusercontent.com/18328038/40558621-2363a184-6054-11e8-8aa9-e9c42d702a5a.png">

**Comment by xvicmanx** [comment]
Hi Max,
Try making the position of the parent relative.

```css

#blockly-container {
    width: 100%;
    height: 100%;
    position: relative;
}

```

**Comment by xvicmanx** [comment]
Let me know if that helps

**Comment by MaxBotta** [comment]
Hey, thanks for the response, but it didn't change anything. Why does it add an offset to the content?

**Comment by MaxBotta** [comment]
Another problem is, that the blockly drawer always has a height of 400px. How can I set the height to 100%?

**Comment by xvicmanx** [comment]
I will take a look at the first issue to see what is going on. The drawer is 400px as this is the min-height we put as default.
For this I could extend the `appereance` property to be able to pass style configuration of the drawer and also add the `style` and `className` properties so you can style the drawer parent if you want in the future.

**Comment by MaxBotta** [comment]
That would be very helpful. Thanks for the effort!

**Comment by xvicmanx** [comment]
I added the `style` and `className` props in the new version `1.6.3`

**Comment by MaxBotta** [comment]
Hey Victor, thanks for implementing the attributes, it helps a lot. But I still have the problem, that the content gets a certain offset from the wrapper. The offset seems to be the samoe as the padding from the left side of the window. It is not possible to set any other position than static to parent elements. Why does the content get an offset from the wrapper? 

Here you can see, that the wrapper is placed correctly, but the content is placed with an offset. It does work in a simple context though, where I dont need to change the position attribute.
![image](https://user-images.githubusercontent.com/18328038/40911966-8f7ab4ea-67f0-11e8-8e47-e2914085beb2.png)

**Comment by MaxBotta** [comment]
Hey Victor, I fixed the problem. The issue was, that I use bootstrap and that the col-sm-12 class has some position settings. I changed it to position:static and that works. I still don't know though, why you are calculating the offset for the content? That way I can never change the position attribute

**Comment by MaxBotta** [comment]
Hey, I still got problems with the offset. Can you explain, what an offset is needed for?

**Comment by xvicmanx** [comment]
It was to positionate the element that was absolute. By removing it everything is drawing correctly? If positive then I will remove that
.

**Comment by MaxBotta** [comment]
Removing the offset function will probably work for me. The problem is that if the parent is relative, it will give the content an offset if the parent has an offset to the left side or upper side. But if the parent is static, it will be placed in the correct position, but it will always stay in the same position. This doesn't work for me, because I have a side menu, which can expand.

Parent is relative:
![image](https://user-images.githubusercontent.com/18328038/41001991-c774aaae-6912-11e8-8a33-fd48c0cc4fab.png)

Parent is static and sidemenu expanded:
![image](https://user-images.githubusercontent.com/18328038/41002156-40eda156-6913-11e8-9412-ab2e5da766e5.png)


Setting the parent to relative and not using the offset function would work.

**Comment by xvicmanx** [comment]
Hello Max, I just pushed a fix with your suggestion. Let me know if that helps.
The latest version now is the `1.6.4`

**Comment by MaxBotta** [comment]
Thanks a lot! I will test it and let you know.
