### ISSUE TITLE
Updating the toolbox with props update don't work

### ISSUE THREAD

**Issue by vportascarta** [xvicmanx/react-blockly-drawer#12]
Hi, I'm using this component for a project with some teachers and we have a problem when we try to update the toolbox. We built a prototype with pure JS and HTML and each activity has several pages with an attach toolbox. Now we want to regroup them in a single react component and we need to change the toolbox without reloading blockly.

The react side seems to work because the xml in DOM is changed when we update the `tools` props but we don't see the update on the interface. However if we run this command in the console after the update, the toolbox interface match the xml in DOM : 

`Blockly.getMainWorkspace().updateToolbox(document.getElementsByTagName("xml")[0])` 

If you need more info let me know.

**Comment by xvicmanx** [comment]
Hello Vincent,
Thanks for reporting this issue.
I will work on a solution.

**Comment by xvicmanx** [comment]
I just published a new version `1.6.6`. Please, let me know if that solves the issue.

**Comment by vportascarta** [comment]
Perfect ! The new version works as expected.
Thanks
