### ISSUE TITLE
Put a setState in the onChange function block the drop of blocks

### ISSUE THREAD

**Issue by vportascarta** [xvicmanx/react-blockly-drawer#14]
I want to get the workspace and code in the state of my blockly wrapper to allow some interactivity with other react components. But each time I put a `setState()` call in the onChange callback, I cannot drop new blocks.

This is my callback function :
```
onWorkspaceChange(code, workspace) {
    this.setState({codeAnswer: code});
    console.log(code, workspace);
  }
```

This is a video showing the problem : https://1drv.ms/v/s!AuXWNhUnO4Q3gaQYXk61jt7MG74p4w

I tried to log the workspace in the same time and I found that the block is added then deleted immediately after.

If you need more info, please let me know.

**Comment by xvicmanx** [comment]
Hi Vicent, 
Could you provide an example of how the component is used to try to replicate and get to a solution? Thanks in advance

**Comment by teleginzhenya** [comment]
@vportascarta hello, it happens because of rerender.
Workaround to fix: 
```javascript
shouldComponentUpdate() {
  return false;
}
```

**Comment by xvicmanx** [comment]
@vportascarta  did that help you?

**Comment by vportascarta** [comment]
Yes it's worked !
But my function is more complicated than yours because I want to update the component when the props update (and block it when only the state changed).
