### ISSUE TITLE
Code for custom block inside while block

### ISSUE THREAD

**Issue by teleginzhenya** [xvicmanx/react-blockly-drawer#15]
@xvicmanx Hi Victor. Thank you for this project.

## Description
I've faced some difficulties with putting my custom block inside while block. 
![image](https://user-images.githubusercontent.com/24455680/42271945-7a01e1d8-7fa6-11e8-8541-1a4ed21d5ef1.png)

On screen all well, however code cannot be generated for this case. Also, code cannot be generated, when custom block inside block (related to while, if, etc.)

This is the error of generating code:
![image](https://user-images.githubusercontent.com/24455680/42272078-d7df85ee-7fa6-11e8-9cd0-729e59ae2534.png)

## Reproduction
https://github.com/teleginzhenya/blockly-custom-blocks-inside

- `git clone https://github.com/teleginzhenya/blockly-custom-blocks-inside.git`
 - `npm install`
 - `npm run start`
 - Get custom block `helloWorld` from `Demo` category
 - Put it inside block (e. g. `while`)

## Expectation
Code should be generated

**Comment by xvicmanx** [comment]
@teleginzhenya thanks for reporting the issue and also for creating an environment to replicate it.
I will take a look as soon as I can to figure out what is happening.

**Comment by xvicmanx** [comment]
@teleginzhenya still figuring out the issue what is failing. However, it seems to work when a string, instead of an array, is returned by the generator function.

```js
 generator: (block) => {
    const message = `'${block.getFieldValue('NAME')}'` || '\'\'';
    const code = `console.log('Hello ${message}')`;
    return code;
  },
```

**Comment by teleginzhenya** [comment]
@xvicmanx hello, thanks for help. I think this problem comes from `node-blockly/browser`

However I found another solution to make custom `while` loop with JS initialization

```javascript
const repeatUntill =  {
  name: 'repeatUntill',
  category: 'Demo',
  block: {
    init: function () {
      this.appendDummyInput()
          .appendField("repeat untill")
      this.appendStatementInput('DO')
          .appendField('do');
      this.setPreviousStatement(true);
      this.setTooltip('here is tooltip');
    },
  },
  generator: (block) => {
    var branch = Blockly.JavaScript.statementToCode(block, 'DO');
    if (Blockly.JavaScript.INFINITE_LOOP_TRAP) {
      branch = Blockly.JavaScript.INFINITE_LOOP_TRAP.replace(/%1/g,
          '\'block_id_' + block.id + '\'') + branch;
    }
    return 'while (notDone()) {\n' + branch + '}\n';
  },
};
```

**Comment by xvicmanx** [comment]
Cool!

**Comment by famigone** [comment]
I [have the same problem or similar](https://github.com/xvicmanx/react-blockly-drawer/issues/19). But I think the problem is in the combination of using previousStatement with returning an array. If I do not use previousStatement I do not have the error ... or if I return a string instead of an array. Any more ideas?
