### ISSUE TITLE
Could not install via npm

### ISSUE THREAD

**Issue by andywindowsmac** [xvicmanx/react-blockly-drawer#16]
Hello, I try install lib via npm, but it's failed on the test.

npm version 6.1.0
node version 10.5.0
[output.txt](https://github.com/xvicmanx/react-blockly-drawer/files/2222090/output.txt)

**Comment by Macilias** [comment]
Same here. Here is the output of npm install:

npm version 6.4.1
node version v10.5.0

> $> npm install
> 
> react-boilerplate@3.6.0 preinstall /Users/username/Programming/github.com/blockly-dev
> npm run npmcheckversion
> 
> 
> react-boilerplate@3.6.0 npmcheckversion /Users/username/Programming/github.com/blockly-dev
> node ./internals/scripts/npmcheckversion.js
> 
> 
> libxmljs@0.18.0 install /Users/username/Programming/github.com/blockly-dev/node_modules/libxmljs
> node-gyp rebuild
> 
>   CC(target) Release/obj.target/libxml/vendor/libxml/buf.o
>   CC(target) Release/obj.target/libxml/vendor/libxml/catalog.o
>   CC(target) Release/obj.target/libxml/vendor/libxml/chvalid.o
>   CC(target) Release/obj.target/libxml/vendor/libxml/dict.o
>   CC(target) Release/obj.target/libxml/vendor/libxml/encoding.o
>   CC(target) Release/obj.target/libxml/vendor/libxml/entities.o
>   CC(target) Release/obj.target/libxml/vendor/libxml/error.o
>   CC(target) Release/obj.target/libxml/vendor/libxml/globals.o
>   CC(target) Release/obj.target/libxml/vendor/libxml/hash.o
>   CC(target) Release/obj.target/libxml/vendor/libxml/HTMLparser.o
> ../vendor/libxml/HTMLparser.c:4403:41: warning: missing field 'begin_pos' initializer [-Wmissing-field-initializers]
>     htmlParserNodeInfo node_info = { 0, };
>                                         ^
> 1 warning generated.
>   CC(target) Release/obj.target/libxml/vendor/libxml/HTMLtree.o
>   CC(target) Release/obj.target/libxml/vendor/libxml/legacy.o
>   CC(target) Release/obj.target/libxml/vendor/libxml/list.o
>   CC(target) Release/obj.target/libxml/vendor/libxml/parser.o
>   CC(target) Release/obj.target/libxml/vendor/libxml/parserInternals.o
>   CC(target) Release/obj.target/libxml/vendor/libxml/pattern.o
>   CC(target) Release/obj.target/libxml/vendor/libxml/relaxng.o
>   CC(target) Release/obj.target/libxml/vendor/libxml/SAX2.o
>   CC(target) Release/obj.target/libxml/vendor/libxml/SAX.o
>   CC(target) Release/obj.target/libxml/vendor/libxml/tree.o
>   CC(target) Release/obj.target/libxml/vendor/libxml/threads.o
>   CC(target) Release/obj.target/libxml/vendor/libxml/uri.o
>   CC(target) Release/obj.target/libxml/vendor/libxml/valid.o
>   CC(target) Release/obj.target/libxml/vendor/libxml/xinclude.o
>   CC(target) Release/obj.target/libxml/vendor/libxml/xlink.o
>   CC(target) Release/obj.target/libxml/vendor/libxml/xmlIO.o
>   CC(target) Release/obj.target/libxml/vendor/libxml/xmlmemory.o
>   CC(target) Release/obj.target/libxml/vendor/libxml/xmlmodule.o
>   CC(target) Release/obj.target/libxml/vendor/libxml/xmlreader.o
>   CC(target) Release/obj.target/libxml/vendor/libxml/xmlregexp.o
>   CC(target) Release/obj.target/libxml/vendor/libxml/xmlsave.o
>   CC(target) Release/obj.target/libxml/vendor/libxml/xmlschemas.o
>   CC(target) Release/obj.target/libxml/vendor/libxml/xmlschemastypes.o
>   CC(target) Release/obj.target/libxml/vendor/libxml/xmlstring.o
>   CC(target) Release/obj.target/libxml/vendor/libxml/xmlunicode.o
>   CC(target) Release/obj.target/libxml/vendor/libxml/xmlwriter.o
>   CC(target) Release/obj.target/libxml/vendor/libxml/xpath.o
> In file included from ../vendor/libxml/xpath.c:462:
> ../vendor/libxml/timsort.h:405:65: warning: comparison of integers of different signs: 'long long' and 'const size_t' (aka 'const unsigned long') [-Wsign-compare]
>     if ((stack_curr == 2) && (stack[0].length + stack[1].length == size)) {
>                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~~~~
> In file included from ../vendor/libxml/xpath.c:476:
> ../vendor/libxml/trionan.c:194:1: warning: unused function 'trio_is_special_quantity' [-Wunused-function]
> trio_is_special_quantity
> ^
> ../vendor/libxml/trionan.c:218:1: warning: unused function 'trio_is_negative' [-Wunused-function]
> trio_is_negative
> ^
> 3 warnings generated.
>   CC(target) Release/obj.target/libxml/vendor/libxml/xpointer.o
>   LIBTOOL-STATIC Release/xml.a
>   CXX(target) Release/obj.target/xmljs/src/libxmljs.o
> In file included from ../src/libxmljs.cc:7:
> In file included from ../src/libxmljs.h:7:
> In file included from ../node_modules/nan/nan.h:196:
> ../node_modules/nan/nan_maybe_43_inl.h:88:15: error: no member named 'ForceSet' in 'v8::Object'
>   return obj->ForceSet(GetCurrentContext(), key, value, attribs);
>          ~~~  ^
> ../node_modules/nan/nan_maybe_43_inl.h:220:17: error: no member named 'CloneElementAt' in 'v8::Array'
>   return array->CloneElementAt(GetCurrentContext(), index);
>          ~~~~~  ^
> In file included from ../src/libxmljs.cc:7:
> In file included from ../src/libxmljs.h:7:
> In file included from ../node_modules/nan/nan.h:202:
> In file included from ../node_modules/nan/nan_new.h:189:
> ../node_modules/nan/nan_implementation_12_inl.h:40:38: error: too few arguments to function call, expected 2, have 1
>   return v8::BooleanObject::New(value).As<v8::BooleanObject>();
>          ~~~~~~~~~~~~~~~~~~~~~~      ^
> /Users/username/.node-gyp/10.5.0/include/node/v8.h:4948:3: note: 'New' declared here
>   static Local<Value> New(Isolate* isolate, bool value);
>   ^
> In file included from ../src/libxmljs.cc:7:
> In file included from ../src/libxmljs.h:7:
> In file included from ../node_modules/nan/nan.h:202:
> In file included from ../node_modules/nan/nan_new.h:189:
> ../node_modules/nan/nan_implementation_12_inl.h:40:60: error: expected '(' for function-style cast or type construction
>   return v8::BooleanObject::New(value).As<v8::BooleanObject>();
>                                           ~~~~~~~~~~~~~~~~~^
> ../node_modules/nan/nan_implementation_12_inl.h:40:62: error: expected expression
>   return v8::BooleanObject::New(value).As<v8::BooleanObject>();
>                                                              ^
> In file included from ../src/libxmljs.cc:7:
> In file included from ../src/libxmljs.h:7:
> ../node_modules/nan/nan.h:822:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
>     return node::MakeCallback(
>                  ^
> /Users/username/.node-gyp/10.5.0/include/node/node.h:171:1: note: 'MakeCallback' has been explicitly marked deprecated here
> NODE_DEPRECATED("Use MakeCallback(..., async_context)",
> ^
> /Users/username/.node-gyp/10.5.0/include/node/node.h:88:20: note: expanded from macro 'NODE_DEPRECATED'
>     __attribute__((deprecated(message))) declarator
>                    ^
> In file included from ../src/libxmljs.cc:7:
> In file included from ../src/libxmljs.h:7:
> ../node_modules/nan/nan.h:836:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
>     return node::MakeCallback(
>                  ^
> /Users/username/.node-gyp/10.5.0/include/node/node.h:164:1: note: 'MakeCallback' has been explicitly marked deprecated here
> NODE_DEPRECATED("Use MakeCallback(..., async_context)",
> ^
> /Users/username/.node-gyp/10.5.0/include/node/node.h:88:20: note: expanded from macro 'NODE_DEPRECATED'
>     __attribute__((deprecated(message))) declarator
>                    ^
> In file included from ../src/libxmljs.cc:7:
> In file included from ../src/libxmljs.h:7:
> ../node_modules/nan/nan.h:850:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
>     return node::MakeCallback(
>                  ^
> /Users/username/.node-gyp/10.5.0/include/node/node.h:157:1: note: 'MakeCallback' has been explicitly marked deprecated here
> NODE_DEPRECATED("Use MakeCallback(..., async_context)",
> ^
> /Users/username/.node-gyp/10.5.0/include/node/node.h:88:20: note: expanded from macro 'NODE_DEPRECATED'
>     __attribute__((deprecated(message))) declarator
>                    ^
> In file included from ../src/libxmljs.cc:7:
> In file included from ../src/libxmljs.h:7:
> ../node_modules/nan/nan.h:1463:31: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
>     return scope.Escape(node::MakeCallback(
>                               ^
> /Users/username/.node-gyp/10.5.0/include/node/node.h:171:1: note: 'MakeCallback' has been explicitly marked deprecated here
> NODE_DEPRECATED("Use MakeCallback(..., async_context)",
> ^
> /Users/username/.node-gyp/10.5.0/include/node/node.h:88:20: note: expanded from macro 'NODE_DEPRECATED'
>     __attribute__((deprecated(message))) declarator
>                    ^
> In file included from ../src/libxmljs.cc:7:
> In file included from ../src/libxmljs.h:7:
> ../node_modules/nan/nan.h:2019:7: error: no viable conversion from 'imp::NativeGetter' (aka 'void (*)(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Value> &)') to 'Local<v8::Name>'
>     , getter_
>       ^~~~~~~
> /Users/username/.node-gyp/10.5.0/include/node/v8.h:204:7: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'imp::NativeGetter' (aka 'void (*)(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Value> &)') to 'const v8::Local<v8::Name> &' for 1st
>       argument
> class Local {
>       ^
> /Users/username/.node-gyp/10.5.0/include/node/v8.h:204:7: note: candidate constructor (the implicit move constructor) not viable: no known conversion from 'imp::NativeGetter' (aka 'void (*)(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Value> &)') to 'v8::Local<v8::Name> &&' for 1st argument
> /Users/username/.node-gyp/10.5.0/include/node/v8.h:208:13: note: candidate template ignored: could not match 'Local<type-parameter-0-0>' against 'void (*)(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Value> &)'
>   V8_INLINE Local(Local<S> that)
>             ^
> /Users/username/.node-gyp/10.5.0/include/node/v8.h:3267:43: note: passing argument to parameter 'name' here
>       Local<Context> context, Local<Name> name,
>                                           ^
> ../src/libxmljs.cc:61:17: error: no member named 'IsDead' in 'v8::V8'
>     if (v8::V8::IsDead())
>         ~~~~~~~~^
> In file included from ../src/libxmljs.cc:3:
> /Users/username/.node-gyp/10.5.0/include/node/v8.h:215:5: error: assigning to 'v8::Context *' from incompatible type 'v8::String *'
>     TYPE_CHECK(T, S);
>     ^~~~~~~~~~~~~~~~
> /Users/username/.node-gyp/10.5.0/include/node/v8.h:169:39: note: expanded from macro 'TYPE_CHECK'
>     *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
>                                       ^~~~~~~~~~~~~~~~~~
> ../node_modules/nan/nan.h:2018:7: note: in instantiation of function template specialization 'v8::Local<v8::Context>::Local<v8::String>' requested here
>       name
>       ^
> 4 warnings and 8 errors generated.
> make: *** [Release/obj.target/xmljs/src/libxmljs.o] Error 1
> gyp ERR! build error 
> gyp ERR! stack Error: `make` failed with exit code: 2
> gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
> gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
> gyp ERR! System Darwin 17.7.0
> gyp ERR! command "/usr/local/Cellar/node/10.5.0_1/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
> gyp ERR! cwd /Users/username/Programming/github.com/blockly-dev/node_modules/libxmljs
> gyp ERR! node -v v10.5.0
> gyp ERR! node-gyp -v v3.8.0
> gyp ERR! not ok 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! libxmljs@0.18.0 install: `node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the libxmljs@0.18.0 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/username/.npm/_logs/2018-09-05T13_26_11_487Z-debug.log

**Comment by andywindowsmac** [comment]
I just downgrade my node and npm:
   "node": "8.1.0"
   "npm": "6.2.0"
It is relate to these issues:
(https://github.com/mo4islona/node-blockly/issues/28)
(https://github.com/znerol/node-xmlshim/issues/5)

**Comment by emreozdincer** [comment]
> npm ERR! Failed at the libxmljs@0.18.0 install script.

A work-around for this error is: https://github.com/znerol/node-xmlshim/pull/8#issuecomment-417824499
