### ISSUE TITLE
Is there a way to dynamically change blocks in general?

### ISSUE THREAD

**Issue by sanjanasrivastava** [xvicmanx/react-blockly-drawer#28]
I have a series of blocks with two dropdown inputs, and I need the options for the second dropdown to be conditioned on the choice made in the first dropdown. Is there a way to achieve this? I do not see an "onChange" for the Block elements. Meanwhile, the workspace element onChange never fires after initialization.

**Comment by xvicmanx** [comment]
Hi @sanjanasrivastava. Can You share a screenshot or small example of your case?

**Comment by sanjanasrivastava** [comment]
Hi, thanks for responding! 

Here's are screenshots of a block I have. The first dropdown field will always have the options it currently has. However, the second dropdown field needs to change based on the value chosen for the first field - choosing an "apple" should lead to "cooked, scrubbed", but choosing a "bowl" should lead to a different list ("scrubbed, broken"). 

![Screenshot (92)](https://user-images.githubusercontent.com/8771633/102142649-663fc000-3e28-11eb-8179-607d81762053.png)
![Screenshot (91)](https://user-images.githubusercontent.com/8771633/102142651-663fc000-3e28-11eb-8900-33ab7b7f3a5c.png)

Here's the code for this block: 

 export const basicUnarySentence = {
     name: 'BasicUnarySentence',
     category: 'Basic Sentences',
     block: {
         init: function () {
             this.jsonInit({
                 message0: '%1 is %2', 
                 args0: [
                     {
                         type: 'field_dropdown',
                         name: 'OBJECT',
                         options: generateDropdownArray(Object.keys(objectLabelToCategory))
                     },
                     {
                         type: 'field_dropdown',
                         name: 'DESCRIPTOR',
                         options: generateDropdownArray(objectCategoryToProperties['apple'])
                     }
                 ],
                 output: null,
                 colour: basicSentenceColor,
                 tooltip: 'Applies a descriptor to an object'
             });
         },
         generator: (block) => {
             const message = `'${block.getFieldValue('DESCRIPTOR')}'` || '\'\'';
             console.log('MESSAGE:', message)
             // const code = `console.log('Hello ${message}')`;
             const code = 'print("hello world")'
             return [code, Blockly.Python.ORDER_MEMBER];
         }
     }
 };

I tried using the workspace onChange function, but it doesn't fire when I change the input value of my block. I did notice that it fires when I add new blocks, but it errs out because of a code generation error (even for the demo block).

**Comment by sanjanasrivastava** [comment]
Actually I just realized that the workspace onChange is firing when I change my custom blocks - but it's erring with "Uncaught Error: Language "Python" does not know how to generate code for block type <my block>". 

But this is happening even for the Demo block provided in the example, which has the generator field defined in Python.

**Comment by xvicmanx** [comment]
@sanjanasrivastava I just merged a PR yo support other languages. Will publish a new version soon

**Comment by sanjanasrivastava** [comment]
Great to hear, thanks!

I am still curious to know if it's possible to change blocks dynamically, though. Each time the workspace changes I can access the XML, but even if I can isolate the change I want to make, I'm unsure of how to change the value of the specific block instance that's already in the workspace.

**Comment by sanjanasrivastava** [comment]
Hi, sorry to bother you but would be great to get some pointers on this. As I showed in the example, if I pull a block into the field and change it away from its default value (apple1) to some other object (e.g. bowl1), I'd like the second dropdown to change accordingly. Is this possible?

Thanks!
Sanjana

**Comment by xvicmanx** [comment]
One question @sanjanasrivastava , do you want  to change the dropdown value or options?

**Comment by sanjanasrivastava** [comment]
The options!

**Comment by xvicmanx** [comment]
Made it work. It was a little tricky
```
import React from 'react';

import Blockly from 'node-blockly/browser';

import BlocklyDrawer, { Block, Category } from 'react-blockly-drawer';

export const basicUnarySentence = {
  name: 'BasicSentence',
  category: 'Basic',
  block: {
    init: function (...arxs) {
      const block = this;
      
      const state = {
        objectValue: 'apple',
      };

      const dropdownGenenators = {
        apple: () => [
          ['Select a object', ''],
          ['Apple desc 1', 'appleDesc1'],
          ['Apple desc 2', 'appleDesc2'],
        ],
        orange: () => [
          ['Select a desc', ''],
          ['Orange desc 1', 'orangeDesc1'],
          ['Orange desc 2', 'orangeDesc2'],
        ],
      };

      this.setOnChange(function(changeEvent) {
        const field = block.getField('DESCRIPTOR');
        const objectValue = block.getFieldValue('OBJECT');
        const descriptorValue = block.getFieldValue('DESCRIPTOR');
        
        field.setValue(objectValue !== state.objectValue ? '' : descriptorValue);
        state.objectValue = objectValue;
      });

      this.jsonInit({
        message0: '%1 is %2',
        args0: [
          {
            type: 'field_dropdown',
            name: 'OBJECT',
            options: (...args) => {
              return [
                ['Select a file', ''],
                ['Apple', 'apple'],
                ['Orange', 'orange'],
              ];
            },
          },
          {
            type: 'field_dropdown',
            name: 'DESCRIPTOR',
            options: () => {
              return dropdownGenenators[state.objectValue]();
            },
          }
        ],
        output: 'String',
        colour: 160,
        tooltip: 'Says Hello',
      });
    },
  },
  generator: (block) => {
    const message = `${block.getFieldValue('DESCRIPTOR')}` || "''";
    const code = console.log(`Hello ${message}`);
    return [code, Blockly.JavaScript.ORDER_MEMBER];
  },
};
class Demo extends React.Component {
  constructor(props) {
    super(props);
  }

  render() {
    return (<div>
      <BlocklyDrawer
        tools={[basicUnarySentence]}
        onChange={(code, workspace) => {
          // console.log(code, workspace);
        }}
        language={Blockly.JavaScript}
        appearance={
          {
            categories: {
              Demo: {
                colour: '270'
              },
            },
          }
        }
      >
        <Category name="Variables" custom="VARIABLE" />
        <Category name="Values">
          <Block type="math_number" />
          <Block type="text" />
        </Category>
      </BlocklyDrawer>
    </div>
    );
  }
}

export default Demo;

```

**Comment by xvicmanx** [comment]
Does this work for you @sanjanasrivastava ?

**Comment by sanjanasrivastava** [comment]
Hi @xvicmanx , I'll be checking this out this evening! Thanks so much for implementing this - I'll let you know later today.

**Comment by sanjanasrivastava** [comment]
Hi @xvicmanx , this is exactly what I needed - thanks so much!!

I imagine similar logic could be used to change the first dropdown field as well. Basically, I'm finding that I need to not only change the options of the second dropdown based on the value of the first dropdown, but the options of the first dropdown based on an external variable that could change at any time. Up until now, I've been having trouble because though I can generate the first dropdown's options functionally, each time that function changes, the whole blockly drawer re-renders and so I lose all my built-up blocks.

But it seems like this method of functional option generation might be able to solve that too by using the block onChange rather than the workspace onChange. If I run into problems I might check in for advice, but this is already immensely helpful, thanks again for spending the time on it :)
