### ISSUE TITLE
Unable to figure out how to load the initial XML ?

### ISSUE THREAD

**Issue by vamsiabishek** [xvicmanx/react-blockly-drawer#8]
Firstly thanks for the blockly component, this component is really simple and easy to work with.

I have a scenario where i load the Blockly drawer then drag and drop few blocks. Every time i make any changes i save the workspaceXML.
When i navigate away from the blockly screen and come back i load the blockly drawer again where i need to display the previously created blocks(i saved the previously created code and workspaceXML) so how do i load that XML when the blockly drawer loads.

Thanyou,
Vamsi

**Comment by xvicmanx** [comment]
Hello, basically what you have to do is pass  property `workspaceXML`. This the xml string of your the workspace you want to inject. I realized I had not published the last version of the package. I just did it.
Could you upgrade your version?

<BlocklyDrawer
      workspaceXML={workspaceXML}
      tools={[helloWorld]}
      onChange={(code, workspace) => {
        console.log(code, workspace);
      }}
    >
      <Category name="Variables" custom="VARIABLE" />
      <Category name="Values">
        <Block type="math_number" />
        <Block type="text" />
      </Category>
    </BlocklyDrawer>

**Comment by xvicmanx** [comment]
@vamsiabishek  let me know if the last comment I wrote helps you.
